/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'choss' at '20/10/15 16:08' with Gradle 2.8
 *
 * @author choss, @date 20/10/15 16:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
